<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Grocery;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        // User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        // Grocery::factory()->create(['name' => 'Butter']);
        // Grocery::factory()->create(['name' => 'Butter (Zero Lactose)']);
        // Grocery::factory()->create(['name' => 'Cheese']);
        // Grocery::factory()->create(['name' => 'Cheese (Zero Lactose)']);
        // Grocery::factory()->create(['name' => 'Chicken']);
        // Grocery::factory()->create(['name' => 'Chicken (Frozen)']);
        // Grocery::factory()->create(['name' => 'Cornbread']);
        // Grocery::factory()->create(['name' => 'Eggs']);
        // Grocery::factory()->create(['name' => 'Milk (Zero Lactose)']);
        // Grocery::factory()->create(['name' => 'Yogurt (Zero Lactose)']);
        // Grocery::factory()->create(['name' => 'Fish']);
        // Grocery::factory()->create(['name' => 'Fish (Frozen)']);
        // Grocery::factory()->create(['name' => 'Tomatoes']);
        // Grocery::factory()->create(['name' => 'Potatoes']);
        // Grocery::factory()->create(['name' => 'Olive Oil']);
        // Grocery::factory()->create(['name' => 'Pepper']);
        // Grocery::factory()->create(['name' => 'Soft Drinks']);
        // Grocery::factory()->create(['name' => 'Snacks']);
        // Grocery::factory()->create(['name' => 'Orange']);
        // Grocery::factory()->create(['name' => 'Grapes']);
        // Grocery::factory()->create(['name' => 'Lettuce']);
        // Grocery::factory()->create(['name' => 'Rice']);
        // Grocery::factory()->create(['name' => 'Garlic']);
        // Grocery::factory()->create(['name' => 'Onion']);
        // Grocery::factory()->create(['name' => 'Apple']);
        // Grocery::factory()->create(['name' => 'Tomato']);
        // Grocery::factory()->create(['name' => 'Juice']);
        // Grocery::factory()->create(['name' => 'Milk']);
        // Grocery::factory()->create(['name' => 'Sugar']);
        // Grocery::factory()->create(['name' => 'Pasta']);
        // Grocery::factory()->create(['name' => 'Tomato Sauce']);
        // Grocery::factory()->create(['name' => 'Grated Cheese']);
        // Grocery::factory()->create(['name' => 'Mayonnaise']);
        // Grocery::factory()->create(['name' => 'Olives']);
        // Grocery::factory()->create(['name' => 'Mozzarella Cheese']);
        // Grocery::factory()->create(['name' => 'Beans']);
        // Grocery::factory()->create(['name' => 'Salt']);
        // Grocery::factory()->create(['name' => 'Cooking Oil']);
        // Grocery::factory()->create(['name' => 'Carrot']);
        // Grocery::factory()->create(['name' => 'Bell Pepper']);
        // Grocery::factory()->create(['name' => 'Potato']);
        // Grocery::factory()->create(['name' => 'Cucumber']);
        // Grocery::factory()->create(['name' => 'Lime']);
        // Grocery::factory()->create(['name' => 'Banana']);
        // Grocery::factory()->create(['name' => 'Avocado']);
        // Grocery::factory()->create(['name' => 'Pear']);
        // Grocery::factory()->create(['name' => 'Yogurt']);
        // Grocery::factory()->create(['name' => 'Margarine']);
        // Grocery::factory()->create(['name' => 'Cocoa Powder']);
        // Grocery::factory()->create(['name' => 'Condensed Milk']);
        // Grocery::factory()->create(['name' => 'Heavy Cream']);
        // Grocery::factory()->create(['name' => 'Bread']);
        // Grocery::factory()->create(['name' => 'White Cheese']);
        // Grocery::factory()->create(['name' => 'Ham']);
        // Grocery::factory()->create(['name' => 'Chicken Breast']);
        // Grocery::factory()->create(['name' => 'Caesar Dressing']);
        // Grocery::factory()->create(['name' => 'Ketchup']);
        // Grocery::factory()->create(['name' => 'Mustard']);
        // Grocery::factory()->create(['name' => 'Soy Sauce']);
        // Grocery::factory()->create(['name' => 'Vinegar']);
        // Grocery::factory()->create(['name' => 'Oregano']);
        // Grocery::factory()->create(['name' => 'Basil']);
        // Grocery::factory()->create(['name' => 'Thyme']);
        // Grocery::factory()->create(['name' => 'Rosemary']);
        // Grocery::factory()->create(['name' => 'Cinnamon']);
        // Grocery::factory()->create(['name' => 'Paprika']);
        // Grocery::factory()->create(['name' => 'Wheat Flour']);
        // Grocery::factory()->create(['name' => 'Corn Starch']);
        // Grocery::factory()->create(['name' => 'Baking Powder']);
        // Grocery::factory()->create(['name' => 'Baking Soda']);
        // Grocery::factory()->create(['name' => 'Beef']);
        // Grocery::factory()->create(['name' => 'Pork']);
        // Grocery::factory()->create(['name' => 'Shrimp']);
        // Grocery::factory()->create(['name' => 'Hamurger Buns']);
        // Grocery::factory()->create(['name' => 'Hot Dog Buns']);
        // Grocery::factory()->create(['name' => 'Tortillas']);
        // Grocery::factory()->create(['name' => 'Pizza Dough']);
        // Grocery::factory()->create(['name' => 'Bagels']);
        // Grocery::factory()->create(['name' => 'Croissants']);
        // Grocery::factory()->create(['name' => 'Pita Bread']);
        // Grocery::factory()->create(['name' => 'Rice Cakes']);
        // Grocery::factory()->create(['name' => 'Granola']);
        // Grocery::factory()->create(['name' => 'Cereal']);
        // Grocery::factory()->create(['name' => 'Corn']);
        // Grocery::factory()->create(['name' => 'Pea']);
        // Grocery::factory()->create(['name' => 'Palm Heart']);
        // Grocery::factory()->create(['name' => 'Vegetable Medley']);
        // Grocery::factory()->create(['name' => 'Frozen Vegetables']);
        // Grocery::factory()->create(['name' => 'Sparkling Water']);
        // Grocery::factory()->create(['name' => 'Soda']);
        // Grocery::factory()->create(['name' => 'Coke']);
        // Grocery::factory()->create(['name' => 'Energy Drink']);
        // Grocery::factory()->create(['name' => 'Tea']);
        // Grocery::factory()->create(['name' => 'Coffee']);
        // Grocery::factory()->create(['name' => 'Soy Juice']);
        // Grocery::factory()->create(['name' => 'Wine']);
        // Grocery::factory()->create(['name' => 'Currant']);
        // Grocery::factory()->create(['name' => 'Toilet Paper']);
        // Grocery::factory()->create(['name' => 'Deodorant']);
        // Grocery::factory()->create(['name' => 'Shampoo']);
        // Grocery::factory()->create(['name' => 'Soap']);
        // Grocery::factory()->create(['name' => 'Toothpaste']);
        // Grocery::factory()->create(['name' => 'Dish Soap']);
        // Grocery::factory()->create(['name' => 'Laundry Detergent']);
        // Grocery::factory()->create(['name' => 'Cotton Swab']);
        // Grocery::factory()->create(['name' => 'Trash Bags']);
        // Grocery::factory()->create(['name' => 'Paper Towels']);
        // Grocery::factory()->create(['name' => 'Sponges']);
        // Grocery::factory()->create(['name' => 'Aluminum Foil']);
        // Grocery::factory()->create(['name' => 'Plastic Wrap']);
        // Grocery::factory()->create(['name' => 'Ziplock Bags']);
        // Grocery::factory()->create(['name' => 'Desinfectant']);
        // Grocery::factory()->create(['name' => 'Coffee Filters']);

        Grocery::factory()->create(['name' => 'Manteiga']);
        Grocery::factory()->create(['name' => 'Manteiga (Zero Lactose)']);
        Grocery::factory()->create(['name' => 'Queijo']);
        Grocery::factory()->create(['name' => 'Queijo (Zero Lactose)']);
        Grocery::factory()->create(['name' => 'Frango']);
        Grocery::factory()->create(['name' => 'Frango (Congelado)']);
        Grocery::factory()->create(['name' => 'Pão de Milho']);
        Grocery::factory()->create(['name' => 'Ovos']);
        Grocery::factory()->create(['name' => 'Leite']);
        Grocery::factory()->create(['name' => 'Leite (Zero Lactose)']);
        Grocery::factory()->create(['name' => 'Iogurte']);
        Grocery::factory()->create(['name' => 'Iogurte (Zero Lactose)']);
        Grocery::factory()->create(['name' => 'Peixe']);
        Grocery::factory()->create(['name' => 'Peixe (Congelado)']);
        Grocery::factory()->create(['name' => 'Tomate']);
        Grocery::factory()->create(['name' => 'Batata']);
        Grocery::factory()->create(['name' => 'Azeite de Oliva']);
        Grocery::factory()->create(['name' => 'Pimenta']);
        Grocery::factory()->create(['name' => 'Refrigerante']);
        Grocery::factory()->create(['name' => 'Laranja']);
        Grocery::factory()->create(['name' => 'Uva']);
        Grocery::factory()->create(['name' => 'Alface']);
        Grocery::factory()->create(['name' => 'Arroz']);
        Grocery::factory()->create(['name' => 'Alho']);
        Grocery::factory()->create(['name' => 'Cebola']);
        Grocery::factory()->create(['name' => 'Maçã']);
        Grocery::factory()->create(['name' => 'Suco']);
        Grocery::factory()->create(['name' => 'Açúcar']);
        Grocery::factory()->create(['name' => 'Macarrão']);
        Grocery::factory()->create(['name' => 'Molho de Tomate']);
        Grocery::factory()->create(['name' => 'Queijo Ralado']);
        Grocery::factory()->create(['name' => 'Maionese']);
        Grocery::factory()->create(['name' => 'Azeitona']);
        Grocery::factory()->create(['name' => 'Muçarela']);
        Grocery::factory()->create(['name' => 'Feijão']);
        Grocery::factory()->create(['name' => 'Sal']);
        Grocery::factory()->create(['name' => 'Óleo']);
        Grocery::factory()->create(['name' => 'Cenoura']);
        Grocery::factory()->create(['name' => 'Pimentão']);
        Grocery::factory()->create(['name' => 'Pepino']);
        Grocery::factory()->create(['name' => 'Limão']);
        Grocery::factory()->create(['name' => 'Banana']);
        Grocery::factory()->create(['name' => 'Abacate']);
        Grocery::factory()->create(['name' => 'Pêra']);
        Grocery::factory()->create(['name' => 'Margarina']);
        Grocery::factory()->create(['name' => 'Achocolatado']);
        Grocery::factory()->create(['name' => 'Leite Condensado']);
        Grocery::factory()->create(['name' => 'Creme de Leite']);
        Grocery::factory()->create(['name' => 'Pão']);
        Grocery::factory()->create(['name' => 'Queijo Branco']);
        Grocery::factory()->create(['name' => 'Presunto']);
        Grocery::factory()->create(['name' => 'Molho Caesar']);
        Grocery::factory()->create(['name' => 'Ketchup']);
        Grocery::factory()->create(['name' => 'Mostarda']);
        Grocery::factory()->create(['name' => 'Molho de Soja']);
        Grocery::factory()->create(['name' => 'Vinagre']);
        Grocery::factory()->create(['name' => 'Orégano']);
        Grocery::factory()->create(['name' => 'Manjericão']);
        Grocery::factory()->create(['name' => 'Canela']);
        Grocery::factory()->create(['name' => 'Páprica']);
        Grocery::factory()->create(['name' => 'Farinha de Trigo']);
        Grocery::factory()->create(['name' => 'Amido de Milho']);
        Grocery::factory()->create(['name' => 'Fermento em Pó']);
        Grocery::factory()->create(['name' => 'Bicarbonato de Sódio']);
        Grocery::factory()->create(['name' => 'Carne Bovina']);
        Grocery::factory()->create(['name' => 'Carne Suína']);
        Grocery::factory()->create(['name' => 'Camarão']);
        Grocery::factory()->create(['name' => 'Pão de Hambúrguer']);
        Grocery::factory()->create(['name' => 'Pão de Cachorro-Quente']);
        Grocery::factory()->create(['name' => 'Massa de Pizza']);
        Grocery::factory()->create(['name' => 'Granola']);
        Grocery::factory()->create(['name' => 'Cereal']);
        Grocery::factory()->create(['name' => 'Milho']);
        Grocery::factory()->create(['name' => 'Ervilha']);
        Grocery::factory()->create(['name' => 'Palmito']);
        Grocery::factory()->create(['name' => 'Seleta de Legumes']);
        Grocery::factory()->create(['name' => 'Seleta de Legumes Congelada']);
        Grocery::factory()->create(['name' => 'Água com Gás']);
        Grocery::factory()->create(['name' => 'Energético']);
        Grocery::factory()->create(['name' => 'Chá']);
        Grocery::factory()->create(['name' => 'Café']);
        Grocery::factory()->create(['name' => 'Suco de Soja']);
        Grocery::factory()->create(['name' => 'Vinho']);
        Grocery::factory()->create(['name' => 'Groselha']);
        Grocery::factory()->create(['name' => 'Papel Higiênico']);
        Grocery::factory()->create(['name' => 'Desodorante']);
        Grocery::factory()->create(['name' => 'Shampoo']);
        Grocery::factory()->create(['name' => 'Sabonete']);
        Grocery::factory()->create(['name' => 'Creme Dental']);
        Grocery::factory()->create(['name' => 'Lava Louças']);
        Grocery::factory()->create(['name' => 'Sabão para Roupa']);
        Grocery::factory()->create(['name' => 'Cotonete']);
        Grocery::factory()->create(['name' => 'Saco de Lixo']);
        Grocery::factory()->create(['name' => 'Papel Toalha']);
        Grocery::factory()->create(['name' => 'Esponja']);
        Grocery::factory()->create(['name' => 'Papel Alumínio']);
        Grocery::factory()->create(['name' => 'Plástico Filme']);
        Grocery::factory()->create(['name' => 'Desinfetante']);
        Grocery::factory()->create(['name' => 'Filtro de Café']);

    }
}
